### ISSUE TITLE
Unable to update package.json version

### ISSUE THREAD

**Issue by CWSites** [Reedyuk/NPM-Version#3]
I'm following the example and the output is successful however if the file is changed it's not being updated in the repo. Am I missing something?

```
    runs-on: ubuntu-latest
    needs: [git-version]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'update package.json version'
        uses: reedyuk/npm-version@1.0.2
        with:
          package: './libs/components/'
          version: '${{ version variable from another action }}'
```

Update: I think my problem was the missinge `package.json` on this line `package: './libs/components/package.json`. I have added that and now made it a little further. However my new issue is I'm getting the following error when trying to update `package.json` with version `alpha-0.0.1`.

```
Error: Command failed: npm version alpha-0.0.1 --prefix ./libs/dot-components/ --no-git-tag-version
```

**Comment by Reedyuk** [comment]
Hi, many thanks for considering using my action 👍 

The action currently doesn't commit the change to the package json, it only changes it locally, i have created this ticket for that feature. https://github.com/Reedyuk/NPM-Version/issues/4
In my current use case, i only needed to modify the package.json as its mainly used for feature branches and when we upload to an npm registry, so this is injected in.

As for the error you have, my guess is you do not need the './' can you try 

```
package: 'libs/components/package.json'
```

There should be more error output too, so if the above doesnt work, i would suggest looking at the logs to see if there is more info.

**Comment by Reedyuk** [comment]
hi @CWSites - can you try and use the latest version 1.1.1, you can now add the property:
```git-tag-version```
And set it to true.
```
      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '1.0.1'
          package: 'subproject-directory/'
          git-tag-version: 'true'
```
